"""
Forecasting models.

Each model has the signature (history, horizon, **context) -> np.ndarray of length
`horizon`, where `history` is a date-indexed Series containing only observations
available at the decision point. Models never receive realised future demand.

Models may receive *known future covariates* through `context` — information the
planner genuinely holds at the decision point, such as a published promotion
calendar. This is not leakage: promotions are decisions taken by the retailer
weeks ahead, not outcomes generated by customers.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def naive(history: pd.Series, horizon: int, **_) -> np.ndarray:
    """Last observed value carried forward. The floor every model must beat."""
    return np.repeat(float(history.iloc[-1]), horizon)


def moving_average(history: pd.Series, horizon: int, window: int = 4, **_) -> np.ndarray:
    return np.repeat(float(history.iloc[-window:].mean()), horizon)


def seasonal_naive(history: pd.Series, horizon: int, season: int = 52, **_) -> np.ndarray:
    """
    Same week last year. A deliberately strong retail baseline: it captures annual
    seasonality for free and, where a promotion calendar happens to align with the
    seasonal lag, captures promotion effects by coincidence rather than by design.
    """
    if len(history) < season:
        return naive(history, horizon)
    return np.array(
        [float(history.iloc[-season + (i % season)]) for i in range(horizon)]
    )


def promo_aware(
    history: pd.Series,
    horizon: int,
    hist_promo: pd.Series | None = None,
    future_promo: pd.Series | None = None,
    window: int = 26,
    **_,
) -> np.ndarray:
    """
    Conditional mean: the mean of recent promotion weeks and the mean of recent
    non-promotion weeks, selected by the published plan for each target week.

    Deliberately minimal. No machine learning and no tuning, so any improvement
    over the baseline is attributable to the promotion information rather than to
    model complexity — which is the effect this project sets out to isolate.

    A secondary effect is unavoidable and worth stating: the 26-week window also
    tracks trend more closely than a 52-week seasonal lag, so part of any gain at
    a growing store comes from the shorter window rather than from promotion
    awareness. The two mechanisms are separated in the results.
    """
    if hist_promo is None or future_promo is None:
        return moving_average(history, horizon, window=window)

    recent = history.iloc[-window:]
    recent_promo = hist_promo.iloc[-window:].astype(bool)

    mean_promo = recent[recent_promo].mean()
    mean_base = recent[~recent_promo].mean()

    # Fall back to the pooled mean if a regime is absent from the window
    pooled = recent.mean()
    mean_promo = pooled if np.isnan(mean_promo) else mean_promo
    mean_base = pooled if np.isnan(mean_base) else mean_base

    return np.array(
        [float(mean_promo if p else mean_base) for p in future_promo.astype(bool)]
    )


MODELS = {
    "naive": naive,
    "seasonal_naive": seasonal_naive,
    "ma4": moving_average,
    "promo_aware": promo_aware,
}
